name: Unittests
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: apt-get update && apt-get install mpich
    - run: python -m unittest tests
